version: '2.1'

services:
  my-todolist:
    image: my-todolist
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017